// !! This file is auto-generated, refer to the icon component story for more info' !!
import { SVGTemplateResult } from 'lit';
import {
  apple,
  facebook,
  instagram,
  linkedin,
  nextDoor,
  twitter,
  youtube,
} from './generated-svgs/brandIcons';
import {
  ballotDrop,
  closeCircle,
  googleLogo,
  officeLogo,
  send,
} from './generated-svgs/customIcons';
import { calendar, clock } from './generated-svgs/outlineIcons';
import {
  addressBook,
  addressCard,
  alignLeft,
  alignRight,
  arrowLeft,
  arrowRight,
  bell,
  book,
  building,
  bullhorn,
  bus,
  calendarDay,
  calendarSolid,
  caretDown,
  caretLeft,
  caretRight,
  caretUp,
  checkCircle,
  checkSquare,
  chevronDown,
  chevronLeft,
  chevronRight,
  chevronUp,
  clockSolid,
  comment,
  exclamationTriangle,
  fax,
  file,
  globe,
  home,
  images,
  infoCircle,
  laptop,
  link,
  mailbox,
  mapMarkerAlt,
  microphone,
  paperclip,
  penNib,
  penSquare,
  questionCircle,
  quoteLeft,
  search,
  timesCircle,
  times,
  volumeUp,
  votingBooth,
  votingLocation,
} from './generated-svgs/solidIcons';

export type IconList = {
  [key: string]: SVGTemplateResult;
};

export const brand: IconList = {
  apple,
  facebook,
  instagram,
  linkedin,
  'next-door': nextDoor,
  twitter,
  youtube,
};

export const custom: IconList = {
  'ballot-drop': ballotDrop,
  'close-circle': closeCircle,
  'google-logo': googleLogo,
  'office-logo': officeLogo,
  send,
};

export const outline: IconList = {
  calendar,
  clock,
};

export const solid: IconList = {
  'address-book': addressBook,
  'address-card': addressCard,
  'align-left': alignLeft,
  'align-right': alignRight,
  'arrow-left': arrowLeft,
  'arrow-right': arrowRight,
  bell,
  book,
  building,
  bullhorn,
  bus,
  'calendar-day': calendarDay,
  'calendar-solid': calendarSolid,
  'caret-down': caretDown,
  'caret-left': caretLeft,
  'caret-right': caretRight,
  'caret-up': caretUp,
  'check-circle': checkCircle,
  'check-square': checkSquare,
  'chevron-down': chevronDown,
  'chevron-left': chevronLeft,
  'chevron-right': chevronRight,
  'chevron-up': chevronUp,
  'clock-solid': clockSolid,
  comment,
  'exclamation-triangle': exclamationTriangle,
  fax,
  file,
  globe,
  home,
  images,
  'info-circle': infoCircle,
  laptop,
  link,
  mailbox,
  'map-marker-alt': mapMarkerAlt,
  microphone,
  paperclip,
  'pen-nib': penNib,
  'pen-square': penSquare,
  'question-circle': questionCircle,
  'quote-left': quoteLeft,
  search,
  'times-circle': timesCircle,
  times,
  'volume-up': volumeUp,
  'voting-booth': votingBooth,
  'voting-location': votingLocation,
};

export const iconList: IconList = {
  ...brand,
  ...custom,
  ...outline,
  ...solid,
};
