image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      nvm install
      yarn
    command: |
      yarn start

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - pranaygp.vscode-css-peek
    - runem.lit-plugin
    - unifiedjs.vscode-mdx
    - streetsidesoftware.code-spell-checker

ports:
  # Used by Storybook
  - port: 6042
    onOpen: open-preview
    visibility: public
