export default [
  {
    text: 'Residents',
    sub: [
      {
        text: 'Find',
        sub: [
          {
            text: 'COVID-19 Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: "Farmer's Markets",
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Hospitals',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Libraries',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'My Supervisorial District',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Parks',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Public WiFi Locations',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Recycling Drop-off',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Services Near Me (SMC Connect)',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Voting Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
        ],
      },
      {
        text: 'Find',
        sub: [
          {
            text: 'COVID-19 Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: "Farmer's Markets",
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Hospitals',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Libraries',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'My Supervisorial District',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Parks',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Public WiFi Locations',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Recycling Drop-off',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Services Near Me (SMC Connect)',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Voting Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
        ],
      },
    ],
  },
  {
    text: 'Business',
    sub: [
      {
        text: 'Find',
        sub: [
          {
            text: 'COVID-19 Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: "Farmer's Markets",
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Hospitals',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Libraries',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'My Supervisorial District',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Parks',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Public WiFi Locations',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Recycling Drop-off',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Services Near Me (SMC Connect)',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Voting Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
        ],
      },
      {
        text: 'Find',
        sub: [
          {
            text: 'COVID-19 Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: "Farmer's Markets",
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Hospitals',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Libraries',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'My Supervisorial District',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Parks',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Public WiFi Locations',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Recycling Drop-off',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Services Near Me (SMC Connect)',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Voting Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
        ],
      },
    ],
  },
];

/* eslint-disable no-useless-escape */
export const jsonData = {
  jsonapi: {
    version: '1.0',
    meta: { links: { self: { href: 'http://jsonapi.org/format/1.0/' } } },
  },
  data: [
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:85f93084-c7d2-4923-9b04-8fbb773a8606',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '1' },
        options: [],
        parent: '',
        provider: 'menu_link_content',
        route: { name: '\u003Cnone\u003E', parameters: [] },
        title: 'Main 1',
        url: '',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:60b33442-f772-42d6-a812-cc19351e939a',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '5' },
        options: { external: true },
        parent: 'menu_link_content:85f93084-c7d2-4923-9b04-8fbb773a8606',
        provider: 'menu_link_content',
        route: { name: '', parameters: [] },
        title: 'Main 1 - sub 1',
        url: 'https://www.npr.org',
        weight: -50,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:faa60829-fcd4-400c-8e86-54989f1f29e4',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '6' },
        options: { external: true },
        parent: 'menu_link_content:85f93084-c7d2-4923-9b04-8fbb773a8606',
        provider: 'menu_link_content',
        route: { name: '', parameters: [] },
        title: 'Main 1 - sub 2',
        url: 'https://www.cnn.com',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:dacbe9fb-f3de-430c-b28a-ff12ebe2deb8',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '7' },
        options: { external: true },
        parent: 'menu_link_content:85f93084-c7d2-4923-9b04-8fbb773a8606',
        provider: 'menu_link_content',
        route: { name: '', parameters: [] },
        title: 'Main 1 - sub 3',
        url: 'https://www.cnn.com',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:ad0e49f8-0e55-44a9-93fa-55683e56af03',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '2' },
        options: [],
        parent: '',
        provider: 'menu_link_content',
        route: { name: '\u003Cnone\u003E', parameters: [] },
        title: 'Main 2',
        url: '',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:09a95b3b-8514-4fc4-a661-e149fdd5fdb2',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '9' },
        options: { external: true },
        parent: 'menu_link_content:ad0e49f8-0e55-44a9-93fa-55683e56af03',
        provider: 'menu_link_content',
        route: { name: '', parameters: [] },
        title: 'Main 2 - sub 1',
        url: 'https://www.opb.org',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:313f3a49-d04d-422b-afb2-f8a28d1136dc',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '8' },
        options: [],
        parent: 'menu_link_content:ad0e49f8-0e55-44a9-93fa-55683e56af03',
        provider: 'menu_link_content',
        route: { name: '\u003Cnone\u003E', parameters: [] },
        title: 'Main 2 - sub 2',
        url: '',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:0ad5d5f7-c471-4a4c-9bd7-dbe365b50ccc',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '11' },
        options: [],
        parent: 'menu_link_content:313f3a49-d04d-422b-afb2-f8a28d1136dc',
        provider: 'menu_link_content',
        route: { name: '\u003Cnone\u003E', parameters: [] },
        title: 'Main 2 - sub 2 - sub 2/1',
        url: '',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:a738378b-441c-4702-958a-1dc6a3982323',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '10' },
        options: [],
        parent: 'menu_link_content:ad0e49f8-0e55-44a9-93fa-55683e56af03',
        provider: 'menu_link_content',
        route: { name: '\u003Cnone\u003E', parameters: [] },
        title: 'Main 2 - sub 3',
        url: '',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:5bb9569d-0dd1-445d-af9b-ecea58f7ad6d',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '3' },
        options: [],
        parent: '',
        provider: 'menu_link_content',
        route: { name: '\u003Cnone\u003E', parameters: [] },
        title: 'Main 3',
        url: '',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:5ff49b41-fca4-4889-b974-9f7dbfdc0ad6',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '12' },
        options: [],
        parent: 'menu_link_content:5bb9569d-0dd1-445d-af9b-ecea58f7ad6d',
        provider: 'menu_link_content',
        route: { name: '\u003Cnone\u003E', parameters: [] },
        title: 'Main 3 - sub 1',
        url: '',
        weight: 0,
      },
    },
    {
      type: 'menu_link_content--menu_link_content',
      id: 'menu_link_content:5bc35f9b-5ddb-41fd-a16c-03af661781a2',
      attributes: {
        description: null,
        enabled: true,
        expanded: false,
        menu_name: 'main',
        meta: { entity_id: '4' },
        options: { external: true },
        parent: '',
        provider: 'menu_link_content',
        route: { name: '', parameters: [] },
        title: 'Main 4',
        url: 'https://www.youtube.com',
        weight: 0,
      },
    },
  ],
  links: { self: { href: 'http://demo.docksal.site/jsonapi/menu_items/main' } },
};
