export default [
  {
    text: 'Residents',
    sub: [
      {
        text: 'Find',
        sub: [
          {
            text: 'COVID-19 Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: "Farmer's Markets",
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Hospitals',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Libraries',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'My Supervisorial District',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Parks',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Public WiFi Locations',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Recycling Drop-off',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Services Near Me (SMC Connect)',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Voting Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
        ],
      },
      {
        text: 'Find',
        sub: [
          {
            text: 'COVID-19 Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: "Farmer's Markets",
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Hospitals',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Libraries',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'My Supervisorial District',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Parks',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Public WiFi Locations',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Recycling Drop-off',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Services Near Me (SMC Connect)',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Voting Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
        ],
      },
    ],
  },
  {
    text: 'Business',
    sub: [
      {
        text: 'Find',
        sub: [
          {
            text: 'COVID-19 Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: "Farmer's Markets",
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Hospitals',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Libraries',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'My Supervisorial District',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Parks',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Public WiFi Locations',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Recycling Drop-off',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Services Near Me (SMC Connect)',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Voting Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
        ],
      },
      {
        text: 'Find',
        sub: [
          {
            text: 'COVID-19 Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: "Farmer's Markets",
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Hospitals',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Libraries',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'My Supervisorial District',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Parks',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Public WiFi Locations',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Recycling Drop-off',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Services Near Me (SMC Connect)',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
          {
            text: 'Voting Information',
            url: '#',
            sub: [
              { text: 'COVID-19 Information', url: '#' },
              { text: "Farmer's Markets", url: '#' },
              { text: 'Hospitals', url: '#' },
              { text: 'Libraries', url: '#' },
              { text: 'My Supervisorial District', url: '#' },
              { text: 'Parks', url: '#' },
              { text: 'Public WiFi Locations', url: '#' },
              { text: 'Recycling Drop-off', url: '#' },
              { text: 'Services Near Me (SMC Connect)', url: '#' },
              { text: 'Voting Information', url: '#' },
            ],
          },
        ],
      },
    ],
  },
];
