image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      yarn
      nvm install $(cat .nvmrc)
      nvm use
      npx playwright install --with-deps
    command: |
      yarn start

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - pranaygp.vscode-css-peek
    - runem.lit-plugin
    - silvenon.mdx
    - streetsidesoftware.code-spell-checker

ports:
  # Used by Storybook
  - port: 6042
    onOpen: open-preview
    visibility: public

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
